
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team01-s24-4pm-8
owner: ucsb-cs156-s24
repo_name: team01-s24-4pm-8
pull_requests: [{"author":{"id":"U_kgDOBdHsdg","is_bot":false,"login":"charlene-patenaude","name":""},"headRefName":"Charlene-PublicHoliday-Controller","number":31,"title":"Charlene public holiday controller and tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-8/pull/31"},{"author":{"id":"U_kgDOBXv2pw","is_bot":false,"login":"rainakakani21","name":""},"headRefName":"Raina-READMEFixes","number":29,"title":"Raina readme fixes","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-8/pull/29"},{"author":{"id":"U_kgDOBdHsdg","is_bot":false,"login":"charlene-patenaude","name":""},"headRefName":"Charlene-PublicHoliday","number":28,"title":"Add Holiday Service and Service Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-8/pull/28"},{"author":{"id":"U_kgDOBdHhMA","is_bot":false,"login":"niyati-m","name":""},"headRefName":"Niyati-Zipcode-Controller","number":27,"title":"Add Zipcode Controller and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-8/pull/27"},{"author":{"id":"U_kgDOBdHhMA","is_bot":false,"login":"niyati-m","name":""},"headRefName":"Niyati-Zipcode","number":24,"title":"Niyati zipcode","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-8/pull/24"},{"author":{"id":"U_kgDOBXv2pw","is_bot":false,"login":"rainakakani21","name":""},"headRefName":"raina-university-controller","number":23,"title":"Add university controller and tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-8/pull/23"},{"author":{"id":"MDQ6VXNlcjkxMjk0MDI1","is_bot":false,"login":"vaaniarora","name":"vaani arora"},"headRefName":"Vaani-Joke-Controller","number":22,"title":"Add Jokes Controller and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-8/pull/22"},{"author":{"id":"U_kgDOBXv2pw","is_bot":false,"login":"rainakakani21","name":""},"headRefName":"raina-university","number":20,"title":"Raina university - add university service ","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-8/pull/20"}]
